#!/bin/sh
#
# fluxbox startup-script:
#
# Lines starting with a '#' are ignored.

# Change your keymap:
# xmodmap "/home/$USER/.Xmodmap"

# Applications you want to run with fluxbox.
# MAKE SURE THAT APPS THAT KEEP RUNNING HAVE AN ''&'' AT THE END.
#
# unclutter -idle 2 &
# wmnd &
# wmsmixer -w &

# enable FAQ icon on desktop
idesk &

# add root access
/usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1 &

#start a conky
sh .conky/conky-startup.sh &

#place network manager on the toolbar
nm-applet &

#place a volumeicon on the toolbar
volumeicon &

#place clipboard on the toolbar
clipit &

#put calendar on the toolbar
orage &

#add touchpad control to toolbar
/opt/extras.ubuntu.com/touchpad-indicator/bin/touchpad-indicator &

#put brightness controller and battery monitor on toolbar
xfce4-power-manager &

#put apt-notifier on the toolbar
ionice -c3 nice -n19 python /usr/bin/apt-notifier.py& disown -h; deartifact-xfce-systray-icons 30 2>&1 1>/dev/null &

#start fehbg to get last background
~/.fehbg

# Debian-local change:
#   - fbautostart has been added with a quick hack to check to see if it
#     exists. If it does, we'll start it up by default.
which fbautostart > /dev/null
if [ $? -eq 0 ]; then
    fbautostart
fi

# And last but not least we start fluxbox.
# Because it is the last app you have to run it with ''exec'' before it.

exec fluxbox
# or if you want to keep a log:
# exec fluxbox -log "/home/demo/.fluxbox/log"
