#! /bin/bash

##########################  LOCATION DIRECTIONS  ########################
## Select where you want your dock to be located                       ##
## Location options:                                                   ##
##       TopCenter, TopLeft, TopRight                                  ##
##       LeftCenter, RightCenter                                       ##
##       BottomCenter, BottomLeft, BottomRight                         ##
## Copy/paste selection to replace "LeftCenter" (if necessary) below   ##
#########################################################################


#set up slit location
sed -i "s/^session.screen0.slit.placement:.*/session.screen0.slit.placement: LeftCenter/" $HOME/.fluxbox/init

fluxbox-remote restart

##########################  LAUNCHER DIRECTIONS  ########################
## STEP 1                                                              ##
## Copy/remove the lines below for the number of launchers you want    ##
## Substitute for "NAME" the name of the application, e.g. "firefox  " ##
## Make the icon smaller (-w 32) or larger (-w 64) if you want         ##
## Save the file to $HOME/.fluxbox/script                              ##
## STEP 2                                                              ##
## Right-click the file and rename it as you like                      ##
## Right-click the file again > Properties, Permissions tab:           ##
##      Check "Allow this file to run as a program"                    ##
## STEP 3                                                              ##
## Create a Menu entry under Look > Docks like this:                   ##
##      [exec] (My dock) {#HOME/.fluxbox/scripts/NAME}                 ##
## To start it automatically on login:                                 ##
## Open the startup file and create two new lines:                     ##
##     #start my dock                                                  ##
##     HOME/.fluxbox/scripts/NAME                                      ##
#########################################################################

#the -x at the end allows the user to delete a launcher with a right click
wmalauncher --desktop-file NAME -w 48 -x &
wmalauncher --desktop-file NAME -w 48 -x &
wmalauncher --desktop-file NAME -w 48 -x &  
wmalauncher --desktop-file NAME -w 48 -x &
