#!/bin/bash

#set up slit location
sed -i 's/^session.screen0.slit.placement:.*/session.screen0.slit.placement: LeftCenter/' $HOME/.fluxbox/init

fluxbox-remote restart

# TOOLTIPS
TTIPS+=" --tooltip-show-delay       250"
TTIPS+=" --tooltip-text-padding     3"
TTIPS+=" --tooltip-border-size		3"
TTIPS+=" --tooltip-foreground-color black"
TTIPS+=" --tooltip-background-color #d3d3d3"

#commands for dock launchers
wmalauncher --command  xfce4-appfinder --icon /usr/local/share/icons/mxfcelogo-rounded.png --tooltip-text "Menu of all applications" $TTIPS --background-color black --border-color black --window-size 48 -x & sleep 0.1
wmalauncher --desktop-file mx-tools.desktop --tooltip-text "Configuration tools for MX Linux" $TTIPS  --background-color black --border-color black --window-size 48 & sleep 0.1
wmalauncher --desktop-file thunar.desktop $TTIPS --background-color black --border-color black --window-size 48 & sleep 0.1
wmalauncher --desktop-file clementine.desktop $TTIPS --background-color black --border-color black --window-size 48 & sleep 0.1
wmalauncher --command thunar /usr/share/mxflux/help/ --icon /usr/share/icons/Moka/48x48/apps/wine-help.png --tooltip-text "Documentation for MX-Fluxbox" $TTIPS --background-color black --border-color black --window-size 48 & sleep 0.1
wmalauncher --desktop-file xfce4-terminal.desktop $TTIPS --background-color black --border-color black --window-size 48 & sleep 0.1
wmalauncher --desktop-file thunderbird.desktop $TTIPS --background-color black --border-color black --window-size 48 & sleep 0.1
wmalauncher --desktop-file firefox.desktop $TTIPS --background-color black --border-color black --window-size 48 & sleep 0.1
