#!/bin/bash

#set up slit location
sed -i 's/^session.screen0.slit.placement:.*/session.screen0.slit.placement: BottomCenter/' $HOME/.fluxbox/init

fluxbox-remote restart

#commands for dock launchers
wmalauncher --command  xfce4-appfinder --icon /usr/local/share/icons/mxfcelogo-rounded_48.png --background-color black --border-color black --window-size 48 -x & sleep 0.1
wmalauncher --desktop-file mx-tools.desktop --background-color black --border-color black --window-size 48 -x & sleep 0.1
wmalauncher --desktop-file thunar.desktop --background-color black --border-color black --window-size 48 -x & sleep 0.1
wmalauncher --desktop-file clementine.desktop --background-color black --border-color black --window-size 48 -x & sleep 0.1
wmalauncher --desktop-file thunderbird.desktop --background-color black --border-color black --window-size 48 -x & sleep 0.1
wmalauncher --desktop-file xfce4-terminal.desktop --background-color black --border-color black --window-size 48 -x & sleep 0.1
wmalauncher --desktop-file firefox.desktop --background-color black --border-color black --window-size 48 -x & sleep 0.1
wmalauncher --command thunar /usr/share/mxflux/help/ --icon /usr/share/icons/Moka/48x48/apps/wine-help.png --background-color black --border-color black --window-size 48 -x & sleep 0.1
