#!/bin/sh
#
# fluxbox startup-script:
#
# Lines starting with a '#' are ignored.

# Applications you want to run with fluxbox.
# MAKE SURE THAT APPS THAT KEEP RUNNING HAVE AN ''&'' AT THE END.

# add an app in the slit
#wmweather -s KPEO & 

#start a compositor if using complicated conkies
#compton &

#add monitors in hidden mode (remove -w to always be visible)
#gkrellm &

# add FAQ icon to desktop
#idesk &

# export Qt variables
export QT_QPA_PLATFORMTHEME=gtk2
export QT_PLATFORMTHEME=gtk2
export QT_PLATFORM_PLUGIN=gtk2

# add root access
/usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1 &

#start a particular conky — example
#conky -p 5 -c ~/.conky/MX-BritPanel/conkyrc_fb &

# provide a screensaver
xfce4-screensaver-command &
xfce4-screensaver &

# start a chat program
#slack &

#add gtk2 variables
gtk-theme-name="Adwaita"
gtk-icon-theme-name="hicolor"
gtk-font-name="Sans 12"

#place network manager on the toolbar
nm-applet &

#place a volumeicon on the toolbar
volumeicon &

#place clipboard on the toolbar
clipit &

#add touchpad control to toolbar
/opt/extras.ubuntu.com/touchpad-indicator/bin/touchpad-indicator &

#put brightness controller and battery monitor on toolbar
xfce4-power-manager &

#put apt-notifier on the toolbar
ionice -c3 nice -n19 python /usr/bin/apt-notifier.py& disown -h; deartifact-xfce-systray-icons 30 2>&1 1>/dev/null &

#start fehbg to get last background selected
~/.fehbg

# Debian-local change:
#   - fbautostart has been added with a quick hack to check to see if it
#     exists. If it does, we'll start it up by default.
which fbautostart > /dev/null
if [ $? -eq 0 ]; then
    fbautostart
fi

# And last but not least we start fluxbox.
# Because it is the last app you have to run it with ''exec'' before it.

exec fluxbox
# or if you want to keep a log:
# exec fluxbox -log "~/.fluxbox/log"
