#!/bin/sh
#
# fluxbox startup-script:
#
# Lines starting with a '#' are ignored.

# Applications you want to run with fluxbox.
# MAKE SURE THAT APPS THAT KEEP RUNNING HAVE AN ''&'' AT THE END.

#start a compositor if using complicated conkies
#compton &

# add launcher for legacy toolbar
#wmalauncher-menu

#add system monitors 
#gkrellm &

# add desktop icons
idesk &

# export Qt variables
export QT_QPA_PLATFORMTHEME=gtk2
export QT_PLATFORMTHEME=gtk2
export QT_PLATFORM_PLUGIN=gtk2

# add root access
/usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1 &

#set the default dock
$HOME/.fluxbox/scripts/DefaultDock.mxdk

# provide a screensaver
xfce4-screensaver-command &
xfce4-screensaver &

#start conky
if [ -f "$HOME/.conky/conky-startup.sh" ]; then
     sh "$HOME/.conky/conky-startup.sh" &
fi

#place network manager on the toolbar
nm-applet &

#place a volumeicon on the toolbar
volumeicon &

#place clipboard on the toolbar
clipit &

#put brightness controller and battery monitor on toolbar
xfce4-power-manager &

#put apt-notifier on the toolbar
ionice -c3 nice -n19 python /usr/bin/apt-notifier.py& disown -h; deartifact-xfce-systray-icons 30 2>&1 1>/dev/null &

#start fehbg to get last background selected
~/.fehbg

# Debian-local change:
#   - fbautostart has been added with a quick hack to check to see if it
#     exists. If it does, we'll start it up by default.
which fbautostart > /dev/null
if [ $? -eq 0 ]; then
    fbautostart
fi

# And last but not least we start fluxbox.
# Because it is the last app you have to run it with ''exec'' before it.

exec fluxbox
# or if you want to keep a log:
# exec fluxbox -log "~/.fluxbox/log"
