#!/bin/sh -e

if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-remove" ] ; then
    apt-mark manual fluxbox \
 mx-idesktool \
 wmalauncher \ 
 moka-icon-theme \
 lxappearance \
 gkrellm \
 mxfb-art \
 mx-dockmaker \
 mxfb-docs \ 
 rofi \
 rofi-calc \ 
 mx-fluxbox-about\ 
 menumaker\
 tint2
fi

#DEBHELPER#
