#!/bin/sh

# localize fluxbox menu 
# 

# fluxbox init file
INIT="$HOME/.fluxbox/init"
# default menu for all none-translated locale
DFLT="$HOME/.fluxbox/menu-mx"
# directory of localized menus 
L10N="/usr/share/mxflux/menu-translations"

# trim region code from LANG
LC="${LANG%%_*}"
# in case LC is empty do nothing
[ x"$LC" = "x" ] && exit 1
#
# default menu is in English
if [ "$LC" != "en" ] && [ -r "$L10N"/menu-mx_$LC ]; then
   MENU="$L10N/menu-mx_$LC" 
   MENU2="$HOME/.fluxbox/menu-mx_$LC"
   if [ ! -e "$MENU2" ]; then
        cp "$MENU" "$MENU2"
   fi
else 
   MENU2="$DFLT"
fi

if [ ! -e "$HOME/.fluxbox/menu-mx_$LC" ]; then
    cp "$MENU" "$HOME/.fluxbox"
fi


if ! grep -sq -E "^session.menuFile:[[:space:]]*(~|$HOME)/$MENU2[[:space:]]*$" "$INIT"; then
   
   sed -i -r "/^(session.menuFile:[[:space:]]*).*/s::\1 ~/$MENU2:"  "$INIT
