#! /bin/bash

#this script was written by the MX Linux Dev Team in January 2020
#its function is to restore the toolbar settings that were in place
#before the user selected the legacy look

TITLE1=$"OK to proceed?"
MSG=$"This will restore the settings that were in place when you selected a legacy toolbar layout."
TITLE2=$"All done!"
END_MSG=$"Log out and back in to complete the change."

##begin msg box
yad --text="


<b>$MSG</b>" --title="$TITLE1" --window-icon=/usr/share/icons/mxflux.png --geometry=400x30 --text-align=center 
##end message box

#restore the archived files, clearing out the folder
cd $HOME/.restore-fluxbox
mv apps init startup $HOME/.fluxbox/

##begin end_msg box
yad --text="


<b>$END_MSG</b>" --title="$TITLE2" --window-icon=/usr/share/icons/mxflux.png --geometry=400x40 --text-align=center 
##end end_msg box

exit
