#! /bin/bash

#this script was written by Jerry3904 January 2020
#its function is to restore the default toolbar settings 

TITLE1=$"OK to proceed?"
MSG=$"This will restore the default toolbar settings."
ECHO1=$"#wmalauncher-menu found"
TITLE2=$"All done!"
END_MSG=$"In order for the changes to take effect, you must now log out and back in."

##begin msg box
yad --text="


<b>$MSG</b>" --title="$TITLE1" --window-icon=/usr/share/icons/mxflux.png --geometry=400x30 --text-align=center 
##end message box

#restore the default files-- needs testing

if grep -q "init" /usr/share/mxflux/.fluxbox/ 2>/dev/null
then

STRING1=$(grep -o 'session.screen0.toolbar.tools:.*' /usr/share/mxflux/.fluxbox/init) 
STRING2=$(grep -o 'session.screen0.slit.placement:.*' /usr/share/mxflux/.fluxbox/init) 
STRING3=$(grep -o 'session.screen0.toolbar.widthPercent:.*' /usr/share/mxflux/.fluxbox/init) 
STRING4=$(grep -o 'session.screen0.toolbar.placement:.*' /usr/share/mxflux/.fluxbox/init) 

sed -i "s/session.screen0.toolbar.tools:.*/$STRING1/" $HOME/.fluxbox/init
sed -i "s/session.screen0.slit.placement:.*/$STRING2/" $HOME/.fluxbox/init
sed -i "s/session.screen0.toolbar.widthPercent:.*/$STRING3/" $HOME/.fluxbox/init
sed -i "s/session.screen0.toolbar.placement:.*/$STRING4/" $HOME/.fluxbox/init

else
echo "There is no /usr/share/mxflux directory"
exit 
fi

#disable wmalauncher
if grep -q "#wmalauncher-menu" $HOME/.fluxbox/startup
then 
echo "$ECHO1"
else 
sed -i "s/wmalauncher-menu/#wmalauncher-menu/" $HOME/.fluxbox/startup

exit
fi

##begin end_msg box
yad --text="


<b>$END_MSG</b>" --title="$TITLE2" --window-icon=/usr/share/icons/mxflux.png --geometry=400x40 --text-align=center 
##end end_msg box

exit
