#! /bin/bash

#this script was written by Jerry3904 January 2020
#its function is to restore the toolbar settings that were in place
#before the user selected the traditional look

MSG=$"This will restore the settings that were in place when you selected a traditional toolbar layout."
END_MSG=$"In order for the changes to take effect, you need now to log out and back in"

##begin msg box
yad --text="


<b>$MSG</b>" --title=$"OK to proceed?" --window-icon=/usr/share/icons/mxflux.png --geometry=400x30 --text-align=center 
##end message box

#restore the archived files, clearing out the folder
cd $HOME/.restore-fluxbox
mv apps init startup $HOME/.fluxbox/

#disable wmalauncher
sed -i "s/wmalauncher/#wmalauncher/" $HOME/.fluxbox/startup

##begin end_msg box
yad --text="


<b>$END_MSG</b>" --title=$"All done!" --window-icon=/usr/share/icons/mxflux.png --geometry=400x40 --text-align=center 
##end end_msg box

exit
