#! /bin/bash

#set up slit location 
sed -i "s/^session.screen0.slit.placement:.*/session.screen0.slit.placement: LeftCenter/" $HOME/.fluxbox/init

fluxbox-remote restart


wmalauncher --desktop-file firefox.desktop -w 48 &  
wmalauncher --desktop-file thunar.desktop -w 48 &
wmalauncher --command fluxbox-remote rootmenu --icon /usr/local/share/icons/mxfcelogo-rounded.png -w 48  &
Center
