#! /bin/bash

#set up slit location 
sed -i "s/^session.screen0.slit.placement:.*/session.screen0.slit.placement: LeftCenter/" $HOME/.fluxbox/init

fluxbox-remote restart

wmalauncher --desktop-file firefox.desktop -w 48 -x &  
wmalauncher --desktop-file thunar.desktop -w 48 -x &
wmalauncher --command fluxbox-remote rootmenu --icon /usr/local/share/icons/mxfcelogo-rounded.png -w 48 -x  &
wmalauncher --desktop-file clementine.desktop -w 48 -x &
wmalauncher --desktop-file thunderbird.desktop -w 48 -x &
wmalauncher --desktop-file vlc.desktop -w 48 -x &
wmalauncher --desktop-file xfce4-terminal.desktop -w 48 -x &
